---
groups:
  - name: image
    jobs:
    - build-task-image
jobs:
- name: build-task-image
  serial: true
  plan:
  - get: repo-image
    trigger: true
  - put: ciimage 
    params:
      build: repo-image/ci/ci_image

resources:
- name: repo-image 
  type: git
  source:
    uri: {{github-git-repo}} 
    branch: master 
    paths: [ci/ci_image/*]
- name: ciimage 
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-create-hub-task-image}}
